### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by purcell**
Hey, thanks for `elm-mapbox` -- I'm just setting about using it for a new project, and wanted to be able to center the initial map. This PR adds this ability, and also a couple of other little tweaks which made sense to me.

(Related to the initial centering, what I was trying previously was issuing a "flyTo" `Cmd` from `init`, but this doesn't work because the command is executed before the map's ports get connected. This feels a bit unnatural, and I think there might be a couple of ways to avoid it.)

### CODE REVIEW

**Comment by gampleman** [comment]
Hi, for initial centering you can already use: https://package.elm-lang.org/packages/gampleman/elm-mapbox/latest/Mapbox-Style#defaultCenter. The problem with the method in this PR is that it will recenter the map to those coordinates rather unpredictably, basically whenever the DOM diffing algorithm decides to. 

Using ports for this is also viable, and the issue you identified is being fixed in #4.

**Comment by purcell** [comment]
> for initial centering you can already use defaultCenter

Ah! How did I miss that? Thanks!

Shall I remove the last commit from this PR, then? I feel like the other changes might still be worth applying.

And re. #4, yes, that looks like a smart fix.

**Comment by gampleman** [comment]
Yes please.

**Comment by purcell** [comment]
Done, thanks!

**Pull request merged**
